### ISSUE TITLE
Pre-built binary

### ISSUE THREAD

**Issue by ecumber** [SciresM/hactool#10]
Hi, I was wondering if you could release a version of this tool that was already built? I have no idea on how to compile it manually. 

If not possible, could you maybe create a video on how to do it?

**Comment by SciresM** [comment]
Pre-built binaries wouldn't be of very much use to you right now -- hactool doesn't come with any keydata, and right now the keydata needs to be baked in at compile-time. There's an open issue about the keydata not being providable via an external file (#6) -- this will be more sensible then.

 I'll be providing pre-built windows binaries on major version releases, the first of which (1.0) will come out after #6 is closed.

**Comment by SciresM** [comment]
So, #6 is solved. Once I do the rest of the required stuff for 1.0 I'll push out a release. (Required stuff being PK21/PK11 support (#4), and improved wrong-keys error output (#2)).
