### ISSUE TITLE
"Invalid NCA header! Are keys correct?"

### ISSUE THREAD

**Issue by falcorr** [SciresM/hactool#100]
Tried my keys, old copies of my keys, other keys, random internet keys. Tried removing the unused lines that produce the warnings. Tried various ages (key requirements) of nsp files. No effect. 

It's been a while but I'm sure I've used the old keys in the same way without an issue. Right now I'm simply trying to output file info. 

What am I missing?

**Comment by SciresM** [comment]
This is a bug tracker, not a support forum. Ask for help on a hacking discord, or something.

**Comment by falcorr** [comment]
I've attempted to google the issue extensively without success. So, you can confirm there's definitely no bug involved? Dare I ask, can I have, you know, a hint as to what I might be looking for?

**Comment by ghost** [comment]
The program is not smart enough to figure out file type on its own. You have to specify it. For nsp, this is `-t pfs0`.

**Comment by barrywilcox** [comment]
> This is a bug tracker, not a support forum. Ask for help on a hacking discord, or something.

I've been using github for many years and this is the 1st time I've seen someone be so blatantly rude to a user of the software.  
I would call you a name that starts with an  A** and ends with a hole, but I'm a civil person...

Next time think of the person behind the keyboard before you type out stuff like that.

**Comment by masagrator** [comment]
This is an issue tracker, not complaints section. Send them on Discord, or something.

**Comment by SciresM** [comment]
> > This is a bug tracker, not a support forum. Ask for help on a hacking discord, or something.
> 
> I've been using github for many years and this is the 1st time I've seen a developer be so blatantly rude to a user of the software. I would call you a name that starts with an A** and ends with a hole, but I'm a civil person...
> 
> Next time think of the person behind the keyboard before you type out stuff like that.

"I would call you a name but I'm a civil person" is not actually a civil thing to say; it is equivalent to calling someone an asshole, it's just a really passive aggressive way to do it. Also, you can say the word asshole, profanity is allowed here.

Anyway, I don't think it's rude to tell people looking for support that support isn't provided here and they should ask on a discord where support is provided -- "you're in the wrong place, seek help elsewhere" saves everyone time.

But yeah, as noted, this is a bug tracker, not a complaints forum. If you'd like to complain, please direct your complaints to an appropriate discord. My DMs are always open if you want to call me an asshole, my handle is SciresM#0524.
