### ISSUE TITLE
PFS0 with --verify option doesn't seem to work

### ISSUE THREAD

**Issue by Myster-Tee** [SciresM/hactool#101]
Hi dear SciresM,

Is the option --verify supposed to work with PFS0 files ? 
I tried on several NSPs but (unlike with XCIs) the output never displays hash nor signature results.

Regards.

**Comment by SciresM** [comment]
No. "nsp" isn't really supported, pfs0 is mostly just for interacting with exefs dumped.

If you call hactool -t pfs0 on an exefs dump, it will print more information than usual.

**Comment by Myster-Tee** [comment]
Much thanks for the reply (and for all your impressive devs).
