### ISSUE TITLE
not your tool, huh?

### ISSUE THREAD

**Issue by eyeonus** [SciresM/hactool#102]
Limitations on exclusive rights: Computer programs54
(a) Making of Additional Copy or Adaptation by Owner of Copy.— Notwithstanding the provisions of section 106, it is not an infringement for the owner of a copy of a computer program to make or authorize the making of another copy or adaptation of that computer program provided:

(1) that such a new copy or adaptation is created as an essential step in the utilization of the computer program in conjunction with a machine and that it is used in no other manner, or

(2) that such new copy or adaptation is for archival purposes only and that all archival copies are destroyed in the event that continued possession of the computer program should cease to be rightful.

(b) Lease, Sale, or Other Transfer of Additional Copy or Adaptation.—Any exact copies prepared in accordance with the provisions of this section may be leased, sold, or otherwise transferred, along with the copy from which such copies were prepared, only as part of the lease, sale, or other transfer of all rights in the program. Adaptations so prepared may be transferred only with the authorization of the copyright owner

Backups are not illegal. Sharing them is.

**Comment by SciresM** [comment]
This tool does not allow for any kind of installation. It is a data inspection/datamining tool.
