### ISSUE TITLE
Games with compressed romfs now published

### ISSUE THREAD

**Issue by SciresM** [SciresM/hactool#109]
I'm usually not really updating hactool any more but this one I will do. This issue is for my implementing that, likely after this weekend.

**Comment by SciresM** [comment]
I tried to do this today and I don't remember how hactool's code works well enough to make it work. Use hactoolnet, I suppose >.>

**Comment by DarkMatterCore** [comment]
@SciresM If you point me in the right direction, I'm willing to implement compressed RomFS support myself. Even rewrite part of the NCA parsing code, if needed/allowed.

Support for sparse NCA sections is something that needs to be taken care of as well.

This should be enough for me to get familiar with these new NCA features and eventually implement them into nxdumptool-rewrite as well.

**Comment by SciresM** [comment]
Hactool's code is garbage and pretty fundamentally unmaintainable at present.

not sure what you mean by "point you in the right direction".

**Comment by DarkMatterCore** [comment]
> Hactool's code is garbage and pretty fundamentally unmaintainable at present.

Not a problem. I'm pretty familiar with the codebase, even in its current state. Which is why I'm also willing to rewrite NCA handling if it's needed.

> not sure what you mean by "point you in the right direction".

Surely Atmosphère already supports both sparse and compressed RomFS sections.

**Comment by SciresM** [comment]
> Surely Atmosphère already supports both sparse and compressed RomFS sections.

I don't actually think it does -- atmosphere does not really need to load NCAs, so why would it? FS reimpl is still in very early/planning stages.
