### ISSUE TITLE
Windows pre compiled version not working

### ISSUE THREAD

**Issue by Litten9370** [SciresM/hactool#110]
I downloaded the pre compiled windows version, but when I open it, it displays a console for a few seconds, then it closes and does nothing. Anyone have an idea of what I'm missing?

**Comment by shchmue** [comment]
it's a console-based program, you'll need to run it with appropriate command-line arguments

**Comment by Litten9370** [comment]
How do I do that?

**Comment by merryhime** [comment]
Unfortunately this is not the right place to learn about how to use a computer.
Any decent beginner computer book should explain how to use the command line.

For a crash course on how to use the command line, perhaps:
* take a look at [this video series](https://www.youtube.com/watch?v=MBBWVgE0ewk&list=PL6gx4Cwl9DGDV6SnbINlVUd0o2xT4JbMu) 
* or this [MDN article](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Understanding_client-side_tools/Command_line)
