### ISSUE TITLE
How to extract title keys from .nsp

### ISSUE THREAD

**Issue by Arthurfogo7** [SciresM/hactool#111]
I'm using NSA/NSP/XCI TO LayeredFS to merge update+base nca. But I need the update title key specifically and the thing with hex editor doesn't make sense to me. Which command I need to extract the title keys from a .nca or .nsp file? (I have both)

**Comment by SciresM** [comment]
The issue tracker isn't a support channel -- for help dumping/extracting your eShop purchases, seek help on discord or whatever.
