### ISSUE TITLE
I need to extract ExeFS from raw file.

### ISSUE THREAD

**Issue by Arthurfogo7** [SciresM/hactool#112]
Hactool extracted an update ExeFS, but as a raw file, I need the contents inside it. It has almost the same size as the base game, but it's not the same. So, how do I extract the files from this raw data?
![Sem título43543645](https://user-images.githubusercontent.com/85951083/182250987-8067700a-dbec-4884-9ead-15ed08cf4e2e.png)
![4525346g](https://user-images.githubusercontent.com/85951083/182250990-7b58dbe4-8f0d-4623-a2b0-a526b64d1f45.png)

**Comment by SciresM** [comment]
1) when extracting exefs from NCA, use --exefsdir=
2) use "hactool -t exefs" to interact with an exefs partition file
3) this issue tracker is for bugs, not support.
