### ISSUE TITLE
Used the 'make' Command, But There Are Some Issues

### ISSUE THREAD

**Issue by P0W3** [SciresM/hactool#115]
Here is what I did.

![image](https://user-images.githubusercontent.com/18279115/210727923-ccaa9e67-02e0-4ffb-99d3-9ee8acaa1a76.png)

It is not happening.

I use Windows (v10.0.19043.2364) (64-bit).

![image](https://user-images.githubusercontent.com/18279115/210728374-ed74c257-d862-4b56-988d-404e4455c500.png)

**Comment by Masamune3210** [comment]
Looks like you are either missing part of the toolchain or something is misconfigured, make cant find gcc

**Comment by P0W3** [comment]
Okay. I got the "GCC" tools for MSYS.

Here is what I did so far. Plus, there are some warnings in this information.

[MSYS_Progress_A9CB5042.txt](https://github.com/SciresM/hactool/files/10531553/MSYS_Progress_A9CB5042.txt)

**Comment by DavidBuchanan314** [comment]
Warnings are not errors, the compilation appears to have completed successfully.
