### ISSUE TITLE
Cannot extract NCA: Error section 0 is corrupted!

### ISSUE THREAD

**Issue by lodgerz** [SciresM/hactool#116]
message deleted

**Comment by masagrator** [comment]
```
Encryption Type:                    Titlekey crypto
```

Your NCA is encrypted and you didn't provide titlekey. Issues are for bug reports, so for further help seek other places, f.e. Nintendo Homebrew discord or gbatemp forum.

**Comment by lodgerz** [comment]
i put title.keys of last switch firmware (15.0) on ~/.switch folder but it still doesn't work.
i also tried to used "--titlekey=title.keys" option but it says: "Key (title.keys) must be 32 hex digits!"

EDIT:
i SOLVED by extracting files from yuzu (Extract RomFS option)
