### ISSUE TITLE
hello help 

### ISSUE THREAD

**Issue by ifyum** [SciresM/hactool#117]
hello i try to inject something inside a folder for zelda totk 
hactoolnet.exe -k prod.keys -t save sav/0000000000000054 --replacefile /slot_05 out/0000000000000054/slot_05
hactoolnet.exe -k prod.keys -t save sav/0000000000000054 --replacefile /slot_05/progress out/0000000000000054/slot_05/progress
how should it be? or is it not taking the '_'

**Comment by masagrator** [comment]
_ is not used by totk. I guess this folder is used by tool that dumped save. Use tool that dumped it to restore save.

**Comment by zemixe** [comment]
"hactoolnet", wrong repository.

**Comment by ifyum** [comment]
> _ is not used by totk. I guess this folder is used by tool that dumped save. Use tool that dumped it to restore save.

It is the route that the extraction left me

**Comment by Masamune3210** [comment]
Either there is a misunderstanding or something is weird, because both yuzu and ryujinx also render the folder name as "slot_0*"

**Comment by SciresM** [comment]
This isn't the appropriate place for this. this isn't even the hactoolnet repository.

**Comment by ifyum** [comment]
the problem was that I needed the extension .sav
