### ISSUE TITLE
Returns error "Failed to match keys" and doesn't extract

### ISSUE THREAD

**Issue by GormAuslander** [SciresM/hactool#118]
I have command window CD'd into the folder with the exe, along with the keys and the xci I'm trying to unpack. I run the command `hactool.exe -k prod.keys totk.xci` and I get a warn that prod.keys doesn't exist, along with a list of "failed to match key" errors.

**Comment by Clearmist** [comment]
Hello Gorm. It's not obvious in the [documentation](https://github.com/SciresM/hactool#usage), but you need to specify the type of your input file. It looks like your file is XCI so add `--intype xci` to your command.
