### ISSUE TITLE
I can't uncompressed main file 

### ISSUE THREAD

**Issue by Flickable** [SciresM/hactool#124]
[main.zip](https://github.com/SciresM/hactool/files/14559122/main.zip)
PS C:\hactool-1.4.0-win> ./hactool --uncompressed=main_uncompressed -t nso0 main
[WARN] prod.keys does not exist.
NSO0:
    Build Id:                       BF9EFF118C39B7E50B67747FD76FF19F00000000000000000000000000000000
    Sections:
        .text:                      00000000-00305000
        .rodata:                    00305000-0054d000
        .rwdata:                    0054d000-00b64000
        .bss:                       00b64000-00c77000
The tool does not recognize the prod.keys file even though it exists. 

PS C:\hactool-1.4.0-win> ./hactool -t keygen -k prod.keys
[WARN] prod.keys does not exist.
[WARN]: Failed to match key
.
.
.
.
.
.
Deriving keys...
--
All derivable keys (using loaded sources):

secure_boot_key                 =...
.
.
.
Done!
In the end, the key file is not recognized.

I also checked the permission of the file, but there was no problem.
PS C:\hactool-1.4.0-win> dir prod.keys
Mode        -a----      

please help me

**Comment by shchmue** [comment]
keys aren’t required for nso decompression. sounds like your first command worked. the warnings are a little confusing-the prod.keys does not exist warning means it’s not present in the default location. failed to match keys means there are keys in the file that hactool doesn’t recognize. everything is working fine. place the key file in /.switch/ in your user folder as mentioned in the readme and the first message will disappear. for the second, use --disablekeywarns.

**Comment by Flickable** [comment]
Oh I see.
Thank you for helping me.
