### ISSUE TITLE
your program is too complicated

### ISSUE THREAD

**Issue by amidevous** [SciresM/hactool#127]
your program is too complicated

what we need is a program that extracts the ExeFS and the RomFS

and that allows to recreate the xci file once the files are modified

we don't even understand how to recreate the xci file

we need something simple with just 2 options

option 1

option 2 regenerate xci

and that's all

as was the case with hacktool3ds for games in 3ds format

**Comment by masagrator** [comment]
This tool does not create XCI at all. What are you even talking about?

It's not for you to decide how someone's program should look like.

**Comment by shchmue** [comment]
It’s named in honor of ctrtool, not whatever you’re talking about. Both are named after model codes for their respective consoles.

The functionality you’re describing would require system patches identical to those used for piracy and so is far outside the scope of this tool.

If you want to replace assets, use layeredfs. If you want to patch code, write IPS patches.

**Comment by SciresM** [comment]
1) this program does extract exefs/romfs, using the --exefsdir and --romfsdir options.

2) this program is an information viewer/extractor, not a regenerator. It does not and never will build xci files (or NCA files, or anything else).

**Comment by amidevous** [comment]
I remind you that this program is the equivalent of pk3ds for the switch

pk3ds did the extraction and recreation of files and allowed you to edit them all and therefore it is your responsibility to put back the same function as that of pkds3 including the fact of recreating the xci file and even the nsz since pk3ds also did the 3ds files trimmed (compressed)

it's been 7 years since the switch came out and you don't even have half of the functionality of pk3ds

**Comment by amidevous** [comment]
but precisely we need this program to recreate the xci file it is extremely important

because without this we cannot share the modifications made in the games

**Comment by masagrator** [comment]
> because without this we cannot share the modifications made in the games

That's completely false. Layeredfs exists, exefs patches exist, nro patches exist. There is zero reasons to share mods via repacked games other than piracy

If game uses one big archive and there is no way to load additional files outside of that archive, share mod as delta patch made with f. e. xdelta3, or share whole package used to repack it so user can do it on their own PC

**Comment by Schaefers** [comment]
I think that guy is trolling, he’s demanding the same stuff here https://github.com/kwsch/pkNX/issues/382#issuecomment-2364129214, using the same 7 years argument..
