### ISSUE TITLE
prod.keys does not exist.

### ISSUE THREAD

**Issue by hawkiq** [SciresM/hactool#132]
I extracted keys from My switch using Lockpick_RCM and file looks like this
```
aes_kek_generation_source = xxxx
aes_key_generation_source = xxxx
bis_kek_source = xxxx
bis_key_00 = xxxx
bis_key_01 = xxxx
bis_key_02 = xxxx
```

I hide all values for a reason

Then I put these file `prod.keys` and `title.keys` beside `hactool.exe`
I managed somehow to exctract game files .nca and .tik
when I try to run this command I keep getting error
```
hactool.exe -k prod.keys --basenca="basegame.nca" --titlekey="MY32BITKEY" --romfsdir="romfs" --exefsdir="exefs" "update.nca"
```
error I face

```
[WARN] prod.keys does not exist.
[WARN]: Failed to match key "bis_kek_source", (value "xxxx")
[WARN]: Failed to match key "bis_key_00", (value "xxxx")
[WARN]: Failed to match key "bis_key_01", (value "xxxx")
[WARN]: Failed to match key "bis_key_02", (value "xxxx")
[WARN]: Failed to match key "bis_key_03", (value "xxxx")
[WARN]: Failed to match key "bis_key_source_00", (value "xxxx")
```

what am missing ?

**Comment by mailwl** [comment]
try to put your file to path C:\Users\YOUR_USERNAME\\.switch\prod.keys  (change YOUR_USERNAME to your own)
probably current directory not in search list

**Comment by Whovian9369** [comment]
If you put `prod.keys` and `title.keys` in either `C:\Users\YOUR_USERNAME\.switch\` (for Windows) or `$HOME/.switch/` (on Linux and Mac), you won't need to provide `-k prod.keys` at all! :)

You will need to create the `.switch/` directory yourself, however.

**Comment by hawkiq** [comment]
Thanks, its works and i extract nac files easily, thanks for help.
