### ISSUE TITLE
Compile issue: Missing mbedtls' CMAC

### ISSUE THREAD

**Issue by SocraticBliss** [SciresM/hactool#15]
aes.o: In function `aes_calculate_cmac':
aes.c:(.text+0x1c5): undefined reference to `mbedtls_cipher_cmac_starts'
aes.c:(.text+0x1d7): undefined reference to `mbedtls_cipher_cmac_update'
aes.c:(.text+0x1e6): undefined reference to `mbedtls_cipher_cmac_finish'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'hactool' failed
make[1]: *** [hactool] Error 1
make[1]: Leaving directory '/mnt/c/GITHUB/SWITCH/hactool'
Makefile:10: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by SciresM** [comment]
Make clean does not currently clean mbedtls -- you'll need to cd mbedtls && make clean, then re-build mbedtls.
