### ISSUE TITLE
The fusee sample payload displays the SBK as U32BE, whereas hactool requires it as U32LE.

### ISSUE THREAD

**Issue by switch-stuff** [SciresM/hactool#16]
Rajkosto's [biskeydump](https://github.com/rajkosto/biskeydump) displays it in little-endian byte order, but since Kate's sample payload is more easily accessible, more people would have dumped their SBK using it.
A good solution would be to attempt derivation once again with endianness reversal if the keyblob MAC is detected as invalid, then if that fails, display the "check SBK/TSEC" error.

**Comment by SciresM** [comment]
No, I'm not going to reverse endianness -- it's up to the user to enter their SBK correctly.
