### ISSUE TITLE
Error: NAX0 key derivation failed. Check SD card seed and relative path?

### ISSUE THREAD

**Issue by MisterSheeple** [SciresM/hactool#17]
The seed and the path are valid. Was attempting to dump Minecraft: Nintendo Switch Edition until I got this.

The NAND dump I got this from is a Switch running on latest FW (5.0.2)

**Comment by TheExpertNoob** [comment]
Have you dumped any other nax0s successfully?

**Comment by TheExpertNoob** [comment]
should be similar to this command:
`hactool -tnax0 --sdseed=<redacted> --sdpath=/registered/00000049/dab7abb85deaab23c04f4660d21c4bf8.nca "F:\Nintendo\Contents\registered\00000049\dab7abb85deaab23c04f4660d21c4bf8.nca" --plaintext="G:\BackupStuff\_NSW\_TEMP\dab7abb85deaab23c04f4660d21c4bf8.nca"`

**Comment by MisterSheeple** [comment]
That didn't quite work. I get the same error.

**Comment by MisterSheeple** [comment]
And to answer your question, no I have never dumped a NAX0 before.

**Comment by SciresM** [comment]
"The seed and the path are valid" -- can't reproduce, just successfully used hactool to decrypt my SD's copy of fire emblem warriors.

**Comment by MisterSheeple** [comment]
Well I don't know why this isn't working. I got my sdseed the way I'm supposed to, it just isn't working. Also, that's not a very good way to reproduce a bug. Try doing the same thing I did. I've heard that only some NAX0 archives work with hactool, so you might want to try Minecraft: Switch Edition, or some other NAX0s.

**Comment by MisterSheeple** [comment]
Closing because the person who was teaching me how to dump NAX0s was wrong and I finally dumped it the right way.
