### ISSUE TITLE
How to get it to work on Mac OS X El Capitan?

### ISSUE THREAD

**Issue by Ofdas23** [SciresM/hactool#29]
Hello there,

I was trying to use this on my mac running firmware version 10.11.6 but there is just a .exe file in the folder of the unpacked release 1.1.0, I know you just provided a hactool version for windows user, it is not supposed to have a .dmg (or any format supported by Mac) file in the folder. That is why I tried to open the .exe file with wineBottler (running windows based programs on Mac) but somehow wineBottler wont react if I open zhe .exe file.

Can someone please say mehow we can use this on Mac? 

I appreciate every answer/possible solution

**Comment by mailwl** [comment]
just compile by youself, if you can. I think, xcode or command line tools should be installed

**Comment by Ofdas23** [comment]
@mailwl And how can we compile it by ourselves?

**Comment by mailwl** [comment]
download source, cd to folder with sources in Terminal, and type `make`. If not work, needed tools not installed. sorry i can't compile by myself. I have mac only on my work

**Comment by Ofdas23** [comment]
@mailwl Thank You, I compiled it, it works now! It’s a little bit hard to use but it works!

**Comment by ihaveamac** [comment]
Install Xcode Command Line Tools with: `xcode-select --install`, then follow the README as usual.
