### ISSUE TITLE
macOS Version

### ISSUE THREAD

**Issue by noX1609** [SciresM/hactool#33]
Hi,

is it possible to use the script on macOS?
Because in releases tab there is only a windows one if i understood correctly.

Another question: Could you please add an example which parameters are necessary to decrypt and extract an xci file?
Would be great because couldn't find a tutorial for that and the GUI's are all only for windows.

Would be really nice if it would work :)

**Comment by ihaveamac** [comment]
Install Xcode Command Line Tools with `xcode-select --install`, then follow the README for building as usual.
