### ISSUE TITLE
Command-line parsing (getopt_long) not working

### ISSUE THREAD

**Issue by ikarsokolov** [SciresM/hactool#36]
I have compiled hactool on Raspberry Pi (raspbian) and command-line parsing is not working.
Hactool always prints usage information and exits with error code with any command line flags supplied.

Everything seems to work fine if variable type for `getopt_long` call is changed form `char` to `int`:
https://github.com/SciresM/hactool/blob/94d55a936bc8d4441886db9be19f292fac2cbcf5/main.c#L124

**Comment by ihaveamac** [comment]
PR was already made fixing this #35

**Comment by ikarsokolov** [comment]
@ihaveamac Ok. I'm closing the issue then.
