### ISSUE TITLE
Will not build in MINGW32

### ISSUE THREAD

**Issue by bigjokker** [SciresM/hactool#37]
In order for it to build needed to change :
    extern int fseeko64 (FILE *__stream, _off64_t __off, int __whence);

to :
    extern int fseeko64 (FILE *__stream, off64_t __off, int __whence);

**Comment by SciresM** [comment]
As someone who builds using mingw32 -- yes, it does build.

You may need to update your GCC, though. Mine is as follows:

```
C:\Users\Michael>gcc --version
gcc (GCC) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
