### ISSUE TITLE
Unable to dump update + base_game.nca

### ISSUE THREAD

**Issue by Eloeri** [SciresM/hactool#47]
I'm using this command line to use the update.nca with the base_game.nca to dump the full game:
`hactool location\of\update.nca --romfsdir=C:\location\of\romfs --exefsdir=C:\location\of\exefs --basenca C:\location\of\base_game.nca`
And I can `-i` the update or the base_game.nca separately and they'll show the correct titlekeys, because I have the titlekeys in the `~/.switch` folder
however when used together with that command line, I get this: `[WARN] Unable to match rights id to titlekey. Update title.keys?`
but again, when I `-i` them separately, their correct titlekeys show up beneath the rightsID in the headers
And all that is output is:
```Saving main to C:\Switch\Games\01007EF00011E000 - Breath of the Wild - Test\exefs\main...
Saving main.npdm to C:\Switch\Games\01007EF00011E000 - Breath of the Wild - Test\exefs\main.npdm...
Saving rtld to C:\Switch\Games\01007EF00011E000 - Breath of the Wild - Test\exefs\rtld...
Saving sdk to C:\Switch\Games\01007EF00011E000 - Breath of the Wild - Test\exefs\sdk...
Saving subsdk0 to C:\Switch\Games\01007EF00011E000 - Breath of the Wild - Test\exefs\subsdk0...
```
and it stops dumping, nothing in `romfs`

**Comment by bakugo** [comment]
hactool doesn't support titlekey encrypted NCAs with the --basenca option for whatever reason, you can work around this by dumping a decrypted version of the base NCA using --plaintext and then using that as the base.

**Comment by Eloeri** [comment]
According to the author, SciresM, it's a known problem, and he posted this [hactool.exe](https://discordapp.com/channels/269333940928512010/414949821003202562/479092159795167232)
