### ISSUE TITLE
Corruption in combining base_game.nca and update.nca to produce final files.

### ISSUE THREAD

**Issue by Eloeri** [SciresM/hactool#48]
I've been trying to dump a full game by combining an `update.nca` and the `base_game.nca` both taken from the SD card for a bit now, and I want to get someone's knowledgeable take on what I could be doing wrong. 

I can correctly dump the `base_game.nca`, as seen by [this](https://i.imgur.com/S816HyG.jpg) image. I have the prod.keys and the title.keys in the correct `~/.switch` folder, so that when running the the `-i` command, there is no error about any title key issues. The same can be seen in [this](https://i.imgur.com/XRXXLG6.jpg) image for the `update.nca`

Here is an image of an `.szs` file when created by just the `base_game.nca`: [image](https://i.imgur.com/kFn8MKo.jpg). The header is clearly marked by the compression algorithm, along with the file type. 

And here is the same file after being created by dumping the `base_game.nca` with the `update.nca`: [image](https://i.imgur.com/zndNF1K.jpg). Nothing is recognizable, just pure corruption.

Here is an image of the command line passed to get these files: [image](https://i.imgur.com/tcy4Gud.jpg). There's a `[warn]` about titlekeys that wasn't present before, but aside from that you wouldn't be able to tell anything was wrong without looking at the files.

If there's a correct way to do this, then I would just love to learn it. 

I've previously been successful in combining an `update.nca` and a `base_game.nca` if they came from the `rawnand.bin` and the sd card respectively.

**Comment by SciresM** [comment]
I would presume this to be a bug. What are the relevant NCAIDs?

**Comment by Eloeri** [comment]
NCAIDs? Would those be different from Title IDs? 

Or are they the sha256 hashes of the `nca`s?. If so, here is the sha256 for Super Mario Odyssey Base: `0F26BD42CAE0E4CEFDA4B5BBF7AE3D50331ACE6BA53295CBCE2656633A59FECD`, and it is for the update: `C0628FB07A89E9050BDA258F74868E8DF2036D9C5E3030EDBEC95E840B4AA89B`. 

And I've forgotten to mention that this happens with all the `base_game.nca` and `update.nca` files which have both come off the SD card.

**Comment by SciresM** [comment]
They're sha256(nca)[:0x10], yeah -- thanks :)

I'll inspect myself asap. I suspect my rights_id parsing code is wrong in the multi-NCA case.

**Comment by SciresM** [comment]
^ accidentally hit close and comment instead of comment.

**Comment by Eloeri** [comment]
Ha, alright. Thank you for taking a look into this, greatly appreciated.

**Comment by SciresM** [comment]
@Eloeri With latest commit, hactool-y c0628fb07a89e9050bda258f74868e8d.nca --basenca=0f26bd42cae0e4cefda4b5bbf7ae3d50.nca succeeds for me, validating the romfs successfully.
