### ISSUE TITLE
BROKEN. NO COMMAND WORKING

### ISSUE THREAD

**Issue by 0xfffffff0075e2040** [SciresM/hactool#49]
when I run 
`Saschas-MBP:HACTOOL Sn0wden$ ./hactool -x mk8.xci -k keys.ini `
`Invalid NCA header! Are keys correct?`
`Done!`
`Saschas-MBP:HACTOOL Sn0wden$`
 when only trying to specify the keys file by running:
`Saschas-MBP:HACTOOL Sn0wden$ ./hactool -k keys.ini`
`unable to open : No such file or directory`
`Saschas-MBP:HACTOOL Sn0wden$ `
the keys.ini file exists. proof:
`Saschas-MBP:HACTOOL Sn0wden$ file keys.ini`
`keys.ini: ASCII text, with very long lines`
`Saschas-MBP:HACTOOL Sn0wden$ `

> macos 10.13.6 (17G65)

**Comment by khang06** [comment]
you need -t xci for xci

**Comment by SciresM** [comment]
1. please do not send all caps.

2. please read the usage statement.

You're looking for hactool -t xci mk8.xci.

Also I suggest using prod.keys instead of keys.ini, especially as keys are not an INI file.
