### ISSUE TITLE
Fail to open romfs (BKTR)

### ISSUE THREAD

**Issue by arbalest876** [SciresM/hactool#50]
I have already built the newest version using source code.

When I try to extract update romfs of Taiko no Tatsujin, I used the command:
hactool -k keys.txt taiko103.nca --titlekey=xxxxxxxx --baseromfs=baseromfs.bin --romfsdir=romfs
I'm sure titlekey and baseromfs have no problem.
Then it looks extracting the romfs files,but when it extracted about 98% files of romfs,the tool will give a massage'fail to open romfs' and stop extarting.
(I extracted the baseromfs,it has no problem,just extracted all files of romfs.)

**Comment by SciresM** [comment]
What NCAID? What Base RomFS? 

Will fix if I can replicate.

**Comment by arbalest876** [comment]
Taiko no Tatsujin Nintendo Switch Version
TITLE ID(titlekey) of base game:0100d9a005ed60000000000000000004(0dbd386f7c4aa50dfe7d6c713c83ab44)
RIGHT ID(titlekey) of update:0100d9a005ed68000000000000000004(075e5df1d08cd6948ed1bd2e03a99a05)

**Comment by SciresM** [comment]
@arbalest876 Please do not include comments containing illegal information. I will buy the games required for me to debug.

Anyway, what NCAIDs? This is necessary information for me, as Rights IDs do not sufficiently specify content.

**Comment by arbalest876** [comment]
Sorry for my last comment.
The NCAID of update 1.0.3 is be0b90a2bf71c641169e0cfe298aa1d2
The NCAID of basegame is 1adf729f7da40d33b068997adbac355c

**Comment by SciresM** [comment]
Thanks! Will investigate.

**Comment by SciresM** [comment]
Just replicated.

`hactool be0b90a2bf71c641169e0cfe298aa1d2.nca --basenca=1adf729f7da40d33b068997adbac355c.nca --romfsdir=rom` succeeds for me.

`hactool be0b90a2bf71c641169e0cfe298aa1d2.nca --baseromfs=romfs_base.bin --romfsdir=rom` failed ("Failed to read file").

Working on finding issue...

**Comment by SciresM** [comment]
...oh, right.

--baseromfs= requires the romfs to have been saved with --raw.

Not actually a hactool bug -- consider using --basenca!

**Comment by arbalest876** [comment]
Thanks,now I can extract the full romfs successfully.

**Comment by SantexTR** [comment]
Hi @SciresM How are you? I want to open the game update and extract the contents.I get this error.

**Note:** cannot save BKTR section without base romfs.

Thanks.

**Edit:** I can extract game files without problems.

Please look.
