### ISSUE TITLE
Failing to verify NCA files(Certain ones)

### ISSUE THREAD

**Issue by gokou340** [SciresM/hactool#56]
Having an issue with hactool, stating that Section 0 and Section 1 are corrupted. This only happens on some, not all. I've checked and verified that some NCAs verify correctly.

I have all keys up to 05, and it is pulling them. I can successfully use nut to convert the NSX to NSP with the supplied titlekey, so I am not sure where the disconnect is.

Not sure where the issue lies.

**Comment by javierbg** [comment]
~~I'm having similar problems with Final Fantasy VII, I also get the "Section 0 and Section 1 are corrupted" message. I'm also unable to extract the update data. The same happens with Cadence of Hyrule.~~

~~My Switch is on 8.0.1 and all my keys are up to date.~~

Sorry, my bad, I had wrong titlekeys

**Comment by SciresM** [comment]
Your keys are probably not actually up to date -- I have successfully extracted Cadence of Hyrule myself.

**Comment by javierbg** [comment]
> Your keys are probably not actually up to date -- I have successfully extracted Cadence of Hyrule myself.

Sorry, it was my fault, edited my comment

**Comment by hexkyz** [comment]
Closing down this issue as it was sorted out.
