### ISSUE TITLE
hactool.exe does not open

### ISSUE THREAD

**Issue by claudiunderthehood** [SciresM/hactool#60]
Everytime i click on it the cmd opens and closes immediatly(i have Python 2.7 and i have tried admin mode too) please help

**Comment by ghost** [comment]
You have to run it in the command line with args.

**Comment by claudiunderthehood** [comment]
How? I already have the keys  files

**Comment by claudiunderthehood** [comment]
I want to convert a xci file, which command do i have to use?

**Comment by ghost** [comment]
Run the program in command prompt. Drag it in.

**Comment by ghost** [comment]
This also can not directly convert .xci files, look for a different program.

**Comment by claudiunderthehood** [comment]
> This also can not directly convert .xci files, look for a different program.

I can't find anything sadly :/

**Comment by ghost** [comment]
https://www.google.com/search?q=xci+to+nsp&rlz=1C1CHBF_enUS810US810&oq=xci+to+&aqs=chrome.0.0j69i60j0j69i57j69i60j0.3109j0j7&sourceid=chrome&ie=UTF-8
Or do you want to convert it to something else?

**Comment by claudiunderthehood** [comment]
> https://www.google.com/search?q=xci+to+nsp&rlz=1C1CHBF_enUS810US810&oq=xci+to+&aqs=chrome.0.0j69i60j0j69i57j69i60j0.3109j0j7&sourceid=chrome&ie=UTF-8
> Or do you want to convert it to something else?

I downloaded the xci file of pokèmon let's go pikachu and i want to run it on Yuzu that i think runs only NSP files, so i wanted to convert it into that

**Comment by ghost** [comment]
This is not directly related to hactool. https://gbatemp.net/threads/official-4nxci-a-tool-for-converting-xci-to-nsp.515341/ can convert to .nsp, but this is unrelated to hactool. Your original issue is because hactool does not have a gui, and it will not be getting one any time soon, so you should probably close this issue.

**Comment by claudiunderthehood** [comment]
i will, thank you!
