### ISSUE TITLE
pfs0 with padding is incorrectly rejected

### ISSUE THREAD

**Issue by bakugo** [SciresM/hactool#70]
hactool rejects pfs0 files and says they're corrupt if the first file's offset isn't 0, but the switch OS has no problem opening these same files. The same probably applies if there's unused space between files but I have not tested it.

**Comment by SciresM** [comment]
Are there *any* instances of official content with first file offset not 0?

**Comment by bakugo** [comment]
Not that I know of, but I haven't really looked into it.

I just thought you'd want the behavior to be consistent with the official one.

**Comment by SciresM** [comment]
I'm fine with matching that behavior, it's just that it's significantly lower priority on my to-do list if no official content is impacted.
