### ISSUE TITLE
Master key revision 7?

### ISSUE THREAD

**Issue by Mc-muffin** [SciresM/hactool#74]
Basically, I'm trying to extract the romfs from a NSP, but the tool says that section 0 and 1 are corrupted, the only thing worth noting is that the Master Key Revision field says ``7 (Unknown)``

**Comment by thomasnet-mc** [comment]
7 (Unknown) is just that it wasn't updated to show 7.x+. Do you have correct keys and is the NCA using Rights ID crypto ?

**Comment by Mc-muffin** [comment]
Oh, I see, that means I would need 7.x+ keys, right? And no, it's using Titlekey crypto.

**Comment by thomasnet-mc** [comment]
Rights ID crypto = titlekey crypto.
And yes, you need the 7 master key and app kaek.

**Comment by Mc-muffin** [comment]
``Rights ID crypto = titlekey crypto.`` Oh, I'm dumb x) 
Well, time to redump the keys. I'll close the issue, if (for some reason) doesn't work I will just reopen it.

**Comment by shchmue** [comment]
an NSP doesn't have a romfs btw you need to extract the NCAs from it with `-t pfs0 --pfs0dir=` then get romfs from the NCAs inside

it sounds like you might've been inadvertently treating an NSP as an NCA

**Comment by Mc-muffin** [comment]
Yep, I'm aware of that, and you are right for some reason I said NSP on my post but meant NCA, sorry :s
And, thomasnet-mc was right after redumping the keys it worked right away! Thanks again both of you :)
