### ISSUE TITLE
nsp(pfs0) read error

### ISSUE THREAD

**Issue by arbalest876** [SciresM/hactool#77]
When I try to use extract taiko no tatsujin v1.0.11 update file(nsp) with the command:
hactool -t pfs0 xxx.nsp --outdir=xxx
It shows 'Error:PFS0 is corrupt!'
Then I open the nsp file in UltraEdit,and cut the ncas manually.The ncas can be decrypted with no problem.
I compare v1.0.11 update file with v1.0.10's,the different is that in v1.0.11,cert and tik files are not  first two files in nsp,they are last two files.So,is this the reason hactool can't read the nsp file?

**Comment by shchmue** [comment]
did you try building a newer commit
https://github.com/SciresM/hactool/commit/2427664682d7470ab8bdeaba3f2cd5f5c7f12577

**Comment by arbalest876** [comment]
Thanks,I built with the newest code and resolved the issue.
