### ISSUE TITLE
Uploading new release with latest commits

### ISSUE THREAD

**Issue by masagrator** [SciresM/hactool#78]
It looks like latest release is now not compatible with newest games from cartridges. So it's not useful anymore for newest releases from eshop and cartridges. But last build from here works correctly with both formats. So maybe it's time to share next release for windows?

**Comment by ecumber** [comment]
Here you go
[hactool.zip](https://github.com/SciresM/hactool/files/3317509/hactool.zip)

**Comment by masagrator** [comment]
Thank you so much.

**Comment by hexkyz** [comment]
Closing down this issue. There will eventually be a new release.
