### ISSUE TITLE
"Failed to match key"

### ISSUE THREAD

**Issue by JustinB77** [SciresM/hactool#79]
So I have Hactool, I've been trying for the past 2 hours to get my SSBU modded and I run into this:
Failed to match key errors running down my cmd

I'm trying my hardest to know whats going on... I've put prod.keys into a .switch folder and i have my gamedump in my Hactool directory. Please someone help!

**Comment by bakugo** [comment]
"Failed to match key" is not your problem, that just shows up whenever you have extra unneeded keys in the prod.keys file (for whatever reason).

What's the size of the file you're trying to extract?

**Comment by JustinB77** [comment]
you mean my nsp correct? 489,475 kb

**Comment by JustinB77** [comment]
sorry if im wrong with anything here, not used to this stuff

**Comment by friedkeenan** [comment]
You might want to censor that picture since sharing keys is illegal

**Comment by JustinB77** [comment]
how please quick XD

**Comment by JustinB77** [comment]
do i just upload a different one with them blacked out or can i do it here

**Comment by JustinB77** [comment]
or we'll just do that as the problem isnt the keys

**Comment by JustinB77** [comment]
ill be back in the morning so sorry if anyine says anything and i cant respond

**Comment by bakugo** [comment]
>489,475 kb

Smash's filesize is over 13gb, not 489mb.

**Comment by JustinB77** [comment]
Thats very strange why it would give me that file do you know of any reason why it would do that? Or do you know of any other thing i could use? I used that SD to NSP thing...

**Comment by JustinB77** [comment]
Well i may have just found something... I dont know how the program would react to this but i realized that i dont have much storage left... i have a hard drive on me to try it again but my switch is taking up my usb slot... any way to unplug and keep the process safe so i can use my hard drive?

**Comment by JustinB77** [comment]
Welp i think i found it... Again, as I'm unfamiliar with programs like this, I pulled a dumb move and didn't know the process took a while to complete... Then again i still didn't have the storage so I'm trying a different computer that has the storage. I've redone almost everything so i should be ok

**Comment by Pysis868** [comment]
To link to what Bakugo said, it can be seen in hactool 1.4.0 `extkeys.c:213#extkeys_initialize_settings` where it retrieves all of the keys with their values from the file first and iterates through that list, mentioning what is not explicitly matched / requested by the program.
Probably not the best message. Can use `--disablekeywarns`
