### ISSUE TITLE
Update .nca Files Extract Doesn't work !

### ISSUE THREAD

**Issue by SantexTR** [SciresM/hactool#81]
Hi @SciresM How are you? I want to open the game update and extract the contents.I get this error.

Note: cannot save BKTR section without base romfs.

Thanks.

Edit: I can extract game files without problems.

Please look.

**Comment by SciresM** [comment]
Select --basenca=<path to base NCA>

If you don't have it, pass the --basefake and/or --onlyupdated options.

**Comment by SantexTR** [comment]
> 
> 
> Select --basenca=
> 
> If you don't have it, pass the --basefake and/or --onlyupdated options.

Would you please write the full command? 
Thank you.

Edit: I was trading according to the options in the .bat file

**Comment by SciresM** [comment]
Read the usage instructions, or seek help elsewhere.

The full command is not possible to share, as it depends on the inputs.

**Comment by SantexTR** [comment]
> Read the usage instructions, or seek help elsewhere.
> 
> The full command is not possible to share, as it depends on the inputs.

Sorry, I tried these, but I didn't. 
*
**Problem**
*

*
**Problem**
*
