### ISSUE TITLE
Failed - Virus detected

### ISSUE THREAD

**Issue by NaturalHarmonia** [SciresM/hactool#94]
I can't download the latest release of this program. What gives?

**Comment by venixtek** [comment]
been trying also and i can't, tried with different browsers.

**Comment by sandhoners123** [comment]
Disable your antivirus

**Comment by sora10pls** [comment]
This was a problem for me as well with the last release, but latest (1.4.0) doesn't have this issue.
Can probably close this @SciresM :)
