### ISSUE TITLE
issues: prod.keys does not exist.

### ISSUE THREAD

**Issue by laotoulyh** [SciresM/hactool#99]
I use hactool.exe -t save -k prod.keys NX-10.1.0_exfat\SYSTEM\save\8000000000000120, it always prompts that prod.keys does not exist. The following prompt is also that the key does not match, but I have put prod.keys In the same directory, and it is effective to decrypt the system smoothly.

https://gbatemp.net/threads/repair-switch-ask-for-help.579276/#post-9303656

**Comment by laotoulyh** [comment]
https://gbatemp.net/threads/repair-switch-ask-for-help.579276/#post-9303656

**Comment by bao3** [comment]
I got the same issue . Please help us. 
I genertated the "prod.keys" "title.keys" by runing Lockpick_RCM.bin .And put them at the same folder as the nsp file and hactool .
